export const ROUTES = {
  SIGNIN: '/sign-in',
  USERS: '/users',
  USER: '/users/:index',
  MAIN: '/',
};

export const ACTIONST_TYPE = {
  ON_CHANGE_PHONE: 'ON_CHANGE_PHONE',
  ON_CHANGE_PASSWORD: 'ON_CHANGE_PASSWORD',

  GET_USERS_START: 'GET_USERS_START',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',

  GET_USER_START: 'GET_USER_START',
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  GET_USER_FAILURE: 'GET_USER_FAILURE',

  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',

  SIGN_OUT: 'SIGN_OUT',

  SORT_USERS: 'SORT_USER',
};
